/*
 * BenJordanLauncherGUI.java
 *
 * Created on Aug 9, 2012, 10:51:54 PM
 * 
 * Written by Andrew Brown
 * 
 * Version 1.0
 * 
 * A program designed to run all of the Ben Jordan games from a single launcher. 
 */
package benjordanlauncher;

import java.io.IOException;
import javax.swing.JOptionPane;

public class BenJordanLauncherGUI extends javax.swing.JFrame {

    BJPath bjpath = new BJPath();
    boolean isSetup = false;

    /** Creates new form BenJordanLauncherGUI */
    public BenJordanLauncherGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jCase1 = new javax.swing.JButton();
        jCase1dx = new javax.swing.JButton();
        jCase2 = new javax.swing.JButton();
        jCase2dx = new javax.swing.JButton();
        jCase3 = new javax.swing.JButton();
        jCase4 = new javax.swing.JButton();
        jCase5 = new javax.swing.JButton();
        jCase6 = new javax.swing.JButton();
        jCover = new javax.swing.JLabel();
        jCase7 = new javax.swing.JButton();
        jCase8 = new javax.swing.JButton();
        jChangeDir = new javax.swing.JButton();
        jToggleSetup = new javax.swing.JButton();

        jFileChooser1.setAcceptAllFileFilterUsed(false);
        jFileChooser1.setCurrentDirectory(new java.io.File("C:\\"));
            jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowOpened(java.awt.event.WindowEvent evt) {
                    formWindowOpened(evt);
                }
            });

            jCase1.setText("Case 1");
            jCase1.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jCase1MouseClicked(evt);
                }
            });

            jCase1dx.setText("Case 1 Deluxe");
            jCase1dx.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jCase1dxMouseClicked(evt);
                }
            });

            jCase2.setText("Case 2");
            jCase2.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jCase2MouseClicked(evt);
                }
            });

            jCase2dx.setText("Case 2 Deluxe");
            jCase2dx.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jCase2dxMouseClicked(evt);
                }
            });

            jCase3.setText("Case 3");
            jCase3.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jCase3MouseClicked(evt);
                }
            });

            jCase4.setText("Case 4");
            jCase4.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jCase4MouseClicked(evt);
                }
            });

            jCase5.setText("Case 5");
            jCase5.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jCase5MouseClicked(evt);
                }
            });

            jCase6.setText("Case 6");
            jCase6.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jCase6MouseClicked(evt);
                }
            });

            jCover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BJTitle.png"))); // NOI18N

            jCase7.setText("Case 7");
            jCase7.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jCase7MouseClicked(evt);
                }
            });

            jCase8.setText("Case 8");
            jCase8.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jCase8MouseClicked(evt);
                }
            });

            jChangeDir.setText("Change Directory");
            jChangeDir.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jChangeDirMouseClicked(evt);
                }
            });

            jToggleSetup.setText("Toggle Setup");
            jToggleSetup.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jToggleSetupMouseClicked(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jToggleSetup, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addComponent(jCase8, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addComponent(jCase1dx, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addComponent(jCase1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addComponent(jCase2, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addComponent(jCase2dx, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addComponent(jCase3, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addComponent(jCase4, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addComponent(jCase5, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addComponent(jCase6, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addComponent(jCase7, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addComponent(jChangeDir, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                    .addGap(14, 14, 14)
                    .addComponent(jCover, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCover, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jCase1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCase1dx)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCase2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCase2dx)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCase3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCase4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCase5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCase6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCase7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCase8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                            .addComponent(jToggleSetup)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jChangeDir)))
                    .addContainerGap())
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

private void jCase1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCase1MouseClicked
    String[] path = new String[]{bjpath.getDefaultPath() + "\\Ben Jordan 1\\"};
    if (isSetup == true) {
        path[0] += "winsetup.exe";
    } else {
        path[0] += "BJ1.exe";
    }

    openGame(path);
}//GEN-LAST:event_jCase1MouseClicked

private void jCase1dxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCase1dxMouseClicked
    String[] path = new String[]{bjpath.getDefaultPath() + "\\Ben Jordan 1 Deluxe\\"};
    if (isSetup == true) {
        path[0] += "winsetup.exe";
    } else {
        path[0] += "BJ1Deluxe.exe";
    }

    openGame(path);
}//GEN-LAST:event_jCase1dxMouseClicked

private void jCase2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCase2MouseClicked
    String[] path = new String[]{bjpath.getDefaultPath() + "\\Ben Jordan 2\\"};
    if (isSetup == true) {
        path[0] += "winsetup.exe";
    } else {
        path[0] += "BJ2.exe";
    }

    openGame(path);
}//GEN-LAST:event_jCase2MouseClicked

private void jCase2dxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCase2dxMouseClicked
    String[] path = new String[]{bjpath.getDefaultPath() + "\\Ben Jordan 2 Deluxe\\"};
    if (isSetup == true) {
        path[0] += "winsetup.exe";
    } else {
        path[0] += "BJ2Deluxe.exe";
    }

    openGame(path);
}//GEN-LAST:event_jCase2dxMouseClicked

private void jCase3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCase3MouseClicked
    String[] path = new String[]{bjpath.getDefaultPath() + "\\Ben Jordan 3\\"};
    if (isSetup == true) {
        path[0] += "winsetup.exe";
    } else {
        path[0] += "BJ3.exe";
    }

    openGame(path);
}//GEN-LAST:event_jCase3MouseClicked

private void jCase4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCase4MouseClicked
    String[] path = new String[]{bjpath.getDefaultPath() + "\\Ben Jordan 4\\"};
    if (isSetup == true) {
        path[0] += "winsetup.exe";
    } else {
        path[0] += "BJ4.exe";
    }

    openGame(path);
}//GEN-LAST:event_jCase4MouseClicked

private void jCase5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCase5MouseClicked
    String[] path = new String[]{bjpath.getDefaultPath() + "\\Ben Jordan 5\\"};
    if (isSetup == true) {
        path[0] += "winsetup.exe";
    } else {
        path[0] += "BJ5.exe";
    }

    openGame(path);
}//GEN-LAST:event_jCase5MouseClicked

private void jCase6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCase6MouseClicked
    String[] path = new String[]{bjpath.getDefaultPath() + "\\Ben Jordan 6\\"};
    if (isSetup == true) {
        path[0] += "winsetup.exe";
    } else {
        path[0] += "BJ6.exe";
    }

    openGame(path);
}//GEN-LAST:event_jCase6MouseClicked

    /* 
     * So, you've changed where you keep your games. No problem! Just click the
     * "Change Directory" button, and choose the new directory where your BJ games
     * are.
     */
private void jChangeDirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChangeDirMouseClicked
    int returnVal = jFileChooser1.showOpenDialog(this); //Open FileChooser.

    if (returnVal == jFileChooser1.APPROVE_OPTION) {
        String path = jFileChooser1.getSelectedFile().getAbsolutePath();
        bjpath.setDefaultPath(path);
    }
}//GEN-LAST:event_jChangeDirMouseClicked

private void jCase7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCase7MouseClicked
    String[] path = new String[]{bjpath.getDefaultPath() + "\\Ben Jordan 7\\"};
    if (isSetup == true) {
        path[0] += "winsetup.exe";
    } else {
        path[0] += "BJ7.exe";
    }

    openGame(path);
}//GEN-LAST:event_jCase7MouseClicked
private void jCase8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCase8MouseClicked
    String[] path = new String[]{bjpath.getDefaultPath() + "\\Ben Jordan 8\\"};
    if (isSetup == true) {
        path[0] += "winsetup.exe";
    } else {
        path[0] += "BJ8.exe";
    }

    openGame(path);
}//GEN-LAST:event_jCase8MouseClicked

private void jToggleSetupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleSetupMouseClicked
    if (isSetup == false) {
        isSetup = true;
        jToggleSetup.setText("Toggle Games");
    } else {
        isSetup = false;
        jToggleSetup.setText("Toggle Setup");
    }
}//GEN-LAST:event_jToggleSetupMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (!bjpath.getSetup()) {
            int returnVal = jFileChooser1.showOpenDialog(this); //Open FileChooser.

            if (returnVal == jFileChooser1.APPROVE_OPTION) {
                String path = jFileChooser1.getSelectedFile().getAbsolutePath();
                bjpath.setDefaultPath(path);
            }
            bjpath.setSetup(true);
        }
    }//GEN-LAST:event_formWindowOpened

//Opens the file specified by the path in the String[]. If the file cannot be
//opened, an error popup is displayed
    private void openGame(String[] path) {
        try {
            Process p = Runtime.getRuntime().exec(path);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Game could not be opened. Are you "
                    + "in the right directory?");
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BenJordanLauncherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BenJordanLauncherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BenJordanLauncherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BenJordanLauncherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BenJordanLauncherGUI().setVisible(true);
            }
        });


    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCase1;
    private javax.swing.JButton jCase1dx;
    private javax.swing.JButton jCase2;
    private javax.swing.JButton jCase2dx;
    private javax.swing.JButton jCase3;
    private javax.swing.JButton jCase4;
    private javax.swing.JButton jCase5;
    private javax.swing.JButton jCase6;
    private javax.swing.JButton jCase7;
    private javax.swing.JButton jCase8;
    private javax.swing.JButton jChangeDir;
    private javax.swing.JLabel jCover;
    private static javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JButton jToggleSetup;
    // End of variables declaration//GEN-END:variables
}
